// <auto-generated />
namespace varsity_w_auth.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class sports : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sports));
        
        string IMigrationMetadata.Id
        {
            get { return "202103041957299_sports"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
