// <auto-generated />
namespace varsity_w_auth.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class nickname : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nickname));
        
        string IMigrationMetadata.Id
        {
            get { return "202104110112094_nickname"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
